console.log("Bienvenue dans CONSOLE.LOG !")
console.log("On va tout de suite commencer avec une liste des chose qu'on peux faire dans la Console.")
console.log("Tape le mot Log pour commencer.")
console.log("Et tu peux aussi contribuer a CONSOLE.LOG sur GitHub.")
console.log("Merci beaucoup utilisateur de Chrome !")